export const PALETTE_STORAGE_KEY = "evalwiz-palette";
export const DEFAULT_PALETTE = "light";

export const PALETTES = [
  {
    value: "light",
    label: "Amrita",
    icon: "palette",
    mood: "Scholarly",
    previewStyle: "linear-gradient(135deg, #f9e7ed 0%, #ffffff 52%, #b01a48 100%)",
    description: "Warm institutional rose with a formal light canvas.",
    surface: "#ffffff",
    border: "#e7d2db",
    text: "#0f172a",
    mutedText: "#64748b",
    accent: "#b01a48",
  },
  {
    value: "classic",
    label: "Classic Mono",
    icon: "sun",
    mood: "Minimal",
    previewStyle: "linear-gradient(135deg, #ffffff 0%, #f5f5f5 52%, #111111 100%)",
    description: "Quiet grayscale surfaces for stripped-back focus.",
    surface: "#ffffff",
    border: "#d4d4d8",
    text: "#111111",
    mutedText: "#52525b",
    accent: "#27272a",
  },
  {
    value: "ocean",
    label: "Ocean Blue",
    icon: "waves",
    mood: "Calm",
    previewStyle: "linear-gradient(135deg, #e0f2fe 0%, #ffffff 52%, #0f766e 100%)",
    description: "Clear blue-green accents for airy academic dashboards.",
    surface: "#ffffff",
    border: "#bae6fd",
    text: "#0f172a",
    mutedText: "#64748b",
    accent: "#0f766e",
  },
  {
    value: "forest",
    label: "Forest Green",
    icon: "trees",
    mood: "Grounded",
    previewStyle: "linear-gradient(135deg, #ecfdf5 0%, #ffffff 52%, #166534 100%)",
    description: "Grounded green tones with a softer campus-like feel.",
    surface: "#ffffff",
    border: "#bbf7d0",
    text: "#0f172a",
    mutedText: "#64748b",
    accent: "#166534",
  },
  {
    value: "aurora",
    label: "Aurora Pop",
    icon: "sparkles",
    mood: "Energetic",
    previewStyle: "linear-gradient(135deg, #faf8ff 0%, #fdf2f8 45%, #4f46e5 100%)",
    description: "Playful but polished contrast for a brighter workspace.",
    surface: "#ffffff",
    border: "#c7d2fe",
    text: "#111827",
    mutedText: "#6b7280",
    accent: "#6366f1",
  },
  {
    value: "linen",
    label: "Linen Gold",
    icon: "sun",
    mood: "Editorial",
    previewStyle: "linear-gradient(135deg, #f8f3e8 0%, #fffdf8 52%, #b7791f 100%)",
    description: "Soft ivory surfaces with muted gold and editorial warmth.",
    surface: "#fffdf8",
    border: "#eadfca",
    text: "#1f2937",
    mutedText: "#786b57",
    accent: "#b7791f",
  },
  {
    value: "dark",
    label: "Dark Night",
    icon: "moon",
    mood: "Formal",
    previewStyle: "linear-gradient(135deg, #020617 0%, #111827 52%, #d05a88 100%)",
    description: "A formal dark workspace with muted rose highlights.",
    surface: "#0f172a",
    border: "#311721",
    text: "#f8fafc",
    mutedText: "#c9a7b7",
    accent: "#d05a88",
  },
  {
    value: "neon",
    label: "Neon Pulse",
    icon: "sparkles",
    mood: "Electric",
    previewStyle: "linear-gradient(135deg, #020617 0%, #312e81 52%, #22d3ee 100%)",
    description: "Cool cobalt and cyan glow for a sharper dark mode.",
    surface: "#0b1220",
    border: "#1e293b",
    text: "#f8fafc",
    mutedText: "#94a3b8",
    accent: "#818cf8",
  },
  {
    value: "obsidian",
    label: "Obsidian Grove",
    icon: "moon",
    mood: "Deep",
    previewStyle: "linear-gradient(135deg, #020403 0%, #0f1712 52%, #22c55e 100%)",
    description: "Blackened surfaces with rich green contrast and depth.",
    surface: "#050706",
    border: "#1d2a22",
    text: "#e5f7ec",
    mutedText: "#9bc4aa",
    accent: "#22c55e",
  },
  {
    value: "ember",
    label: "Ember Noir",
    icon: "flame",
    mood: "Cinematic",
    previewStyle: "linear-gradient(135deg, #140a08 0%, #3f1d13 52%, #f97316 100%)",
    description: "Smoky charcoal with ember-orange highlights for warmth.",
    surface: "#120a08",
    border: "#4a2315",
    text: "#f8ebe5",
    mutedText: "#d0b1a6",
    accent: "#f97316",
  },
  {
    value: "harbor",
    label: "Harbor Night",
    icon: "moon",
    mood: "Nocturne",
    previewStyle: "linear-gradient(135deg, #03131f 0%, #123247 52%, #2dd4bf 100%)",
    description: "Atlantic navy surfaces with sea-glass teal contrast.",
    surface: "#081722",
    border: "#214055",
    text: "#e7f6fb",
    mutedText: "#91afbf",
    accent: "#2dd4bf",
  },
  {
    value: "slate-frost",
    label: "Slate Frost",
    icon: "moon",
    mood: "Glacial",
    previewStyle: "linear-gradient(135deg, #0b1120 0%, #202b46 52%, #93c5fd 100%)",
    description: "Soft graphite surfaces with icy blue accents.",
    surface: "#0d1423",
    border: "#2b3a55",
    text: "#eef5ff",
    mutedText: "#a6b8d5",
    accent: "#93c5fd",
  },
];

const DARK_PALETTES = new Set(["dark", "neon", "obsidian", "ember", "harbor", "slate-frost"]);

export function isPaletteTheme(value) {
  return PALETTES.some((palette) => palette.value === value);
}

export function isDarkPaletteTheme(value) {
  return DARK_PALETTES.has(value);
}
